export const QUERY_KEYS = {
  GET_USER_DETAILS: "GET_USER_DETAILS",
  EXAM_DETAILS: "EXAM_DETAILS",
  USER: "USER",
  BLACK_LIST_AGENTS: "BLACK_LIST_AGENTS",
  BLACKLISTED_CHECK: "BLACKLISTED_CHECK",
  PAYMENT_RECEIPT_VIEW: "PAYMENT_RECEIPT_VIEW",
  AGING_DISCREPANCY: "AGING_DISCREPANCY",
  CATEGORIES: "CATEGORIES",

  //RESCHEDULE
  RESCHEDULE_USER: "RESCHEDULE_USER",
  RESCHEDULE_LIST: "RESCHEDULE_LIST",
  RESCHEDULE_RAISE: "RESCHEDULE_RAISE",
  RESCHEDULE_APPROVE: "RESCHEDULE_APPROVE",
  EXAM_DETAILS_RAISE: "EXAM_DETAILS_RAISE",

  //SERVICING
  GET_ENDORSEMENT_DISCREPANCY_LIST: "GET_ENDORSEMENT_DISCREPANCY_LIST",

  //EXAM-CONFIG
  LIST_EXAM_CONFIG: "LIST_EXAM_CONFIG",
  EXAM_QUESTIONS_LISTING:"EXAM_QUESTIONS_LISTING",
};
