import { GraduationCap, Hourglass } from "lucide-react";
import {
  HiAcademicCap,
  HiAdjustments,
  HiDocumentText,
  HiExclamationCircle,
  HiIdentification,
  HiPresentationChartBar,
  HiUser,
  HiUserGroup,
} from "react-icons/hi";
import {
  HiClipboardDocumentList,
  HiCog,
  HiDocumentMagnifyingGlass,
  HiDocumentPlus,
  HiMiniBuildingLibrary,
  HiMiniClipboardDocumentList,
  HiMiniCreditCard,
  HiMiniTrophy,
  HiMiniUserMinus,
  HiSwatch,
  HiUsers,
  HiViewColumns,
} from "react-icons/hi2";

const ICONS = {
  "Profile Details": HiUser,
  "Bank Details": HiMiniBuildingLibrary,
  "Nominee Details": HiUserGroup,
  Documents: HiDocumentText,
  "CKYC Verification": HiIdentification,
  Consent: HiMiniClipboardDocumentList,
  Payment: HiMiniCreditCard,
  "Exam Details": HiAcademicCap,
  Training: HiPresentationChartBar,
  Discrepancy: HiExclamationCircle,
  Certified: HiMiniTrophy,
  NOC: HiMiniUserMinus,
};

const SIDE_MENU = [
  {
    id: 1,
    name: "Masters",
    slug: "masters",
    submenus: [
      {
        id: 11,
        name: "Agent Master",
        slug: "agent-master",
        route: "agent-master",
        icon: null,
        parent_id: 1,
      },
      {
        id: 12,
        name: "Transaction Master",
        slug: "transaction-master",
        route: "transaction-master",
        icon: null,
        parent_id: 1,
      },
      {
        id: 13,
        name: "Training Master",
        slug: "training-master",
        route: "training-master",
        icon: null,
        parent_id: 1,
      },
      {
        id: 14,
        name: "IFSC Master",
        slug: "ifsc-master",
        route: "ifsc-master",
        icon: null,
        parent_id: 1,
      },
      {
        id: 15,
        name: "Pincode Master",
        slug: "pincode-master",
        route: "pincode-master",
        icon: null,
        parent_id: 1,
      },
      {
        id: 16,
        name: "Stage Utility",
        slug: "utility-master",
        route: "utility-master",
        icon: null,
        parent_id: 1,
      },
      {
        id: 17,
        name: "Role-Based Charges",
        slug: "role-based-charges",
        route: "role-based-charges",
        icon: null,
        parent_id: 1,
      },
      {
        id: 18,
        name: "Exam-pending",
        slug: "exam-pending",
        route: "exam-pending",
        icon: null,
        parent_id: 1,
      },
      {
        id: 19,
        name: "Blacklisted Agents",
        slug: "blacklisted-agents",
        route: "blacklisted-agents",
        icon: null,
        parent_id: 1,
      },
      {
        id: 20,
        name: "Payment Receipt",
        slug: "payment-receipt-master",
        route: "payment-receipt-master",
        icon: null,
        parent_id: 1,
      },
      {
        id: 21,
        name: "Aging Discrepancy",
        slug: "aging-descrepancy",
        route: "aging-descrepancy",
        icon: null,
        parent_id: 1,
      },
      // {
      //   id: 32,
      //   name: "Reschedule Exam",
      //   slug: "reschedule-exam",
      //   route: "reschedule-exam",
      //   icon: null,
      //   parent_id: 1,
      // },
    ],
  },

  {
    id: 2,
    name: "User Management",
    slug: "user-management-list",
    submenus: [
      {
        id: 21,
        name: "Role Master",
        slug: "role-master",
        route: "role-master",
        icon: null,
        parent_id: 2,
      },
      {
        id: 22,
        name: "Access Control",
        slug: "access-control",
        route: "access-control",
        icon: null,
        parent_id: 2,
      },
      {
        id: 23,
        name: "Create User",
        slug: "user-management",
        route: "create-user",
        icon: null,
        parent_id: 2,
      },
    ],
  },
  {
    id: 3,
    name: "Reports",
    slug: "reports",
    submenus: [
      {
        id: 31,
        name: "IRDAI Report",
        slug: "irdai-report",
        route: "irdai-report",
        icon: null,
        parent_id: 3,
      },
    ],
  },
  {
    id: 4,
    name: "Bulk Upload",
    slug: "bulk-upload-list",
    submenus: [
      {
        id: 41,
        name: "Payment",
        slug: "payment-bulk-upload",
        route: "bulk-upload",
        icon: null,
        parent_id: 4,
      },
      {
        id: 42,
        name: "Agent Lead Upload",
        slug: "agent-lead-upload",
        route: "lead-upload",
        icon: null,
        parent_id: 4,
      },
      {
        id: 43,
        name: "Certified Agent",
        slug: "certified-agent-bulk-upload",
        route: "agent-bulk-upload",
        icon: null,
        parent_id: 4,
      },
      {
        id: 44,
        name: "Exam Date",
        slug: "exam-date-bulk-upload",
        route: "exam-date-bulk-upload",
        icon: null,
        parent_id: 4,
      },
      {
        id: 45,
        name: "Exam Result",
        slug: "exam-result-bulk-upload",
        route: "exam-result-bulk-upload",
        icon: null,
        parent_id: 4,
      },
    ],
  },
  {
    id: 5,
    name: "Exam Config",
    slug: "exam-config-listing",
    submenus: [
      {
        id: 41,
        name: "Exam Config Listing",
        slug: "exam-config-listing",
        route: "exam-config-listing",
        icon: null,
        parent_id: 5,
      },
      {
        id: 42,
        name: "Exam Questions",
        slug: "exam-questions",
        route: "exam-questions",
        icon: null,
        parent_id: 5,
      },
    ],
  },
  {
    id: 6,
    name: "Discrepency List",
    slug: "discrepency-list",
    route: "discrepancy-listing",
    icon: null,
  },

  {
    id: 7,
    name: "NOC List",
    slug: "noc-list",
    route: "noc",
    icon: null,
  },
  {
    id: 8,
    name: "Servicing Module",
    slug: "servicing-module",
    submenus: [
      {
        id: 81,
        name: "Servicing Module",
        slug: "servicing-module",
        route: "servicing-module",
        icon: null,
        parent_id: 8,
      },

      {
        id: 82,
        name: "Actionable",
        slug: "status-tracking-actionable",
        route: "status-tracking-actionable",
        icon: null,
        parent_id: 8,
      },
      {
        id: 83,
        name: "Non Actionable",
        slug: "status-tracking-non-actionable",
        route: "status-tracking-non-actionable",
        icon: null,
        parent_id: 8,
      },
    ],
  },
  {
    id: 9,
    name: "Payment Waiver",
    slug: "payment-waiver",
    route: "payment-waiver",
    icon: null,
  },
  {
    id: 10,
    name: "Settings",
    slug: "settings",
    submenus: [
      {
        id: 101,
        name: "Menu Master",
        slug: "menu-master",
        route: "menu-master",
        icon: null,
        parent_id: 9,
      },
      {
        id: 102,
        name: "Themes",
        slug: "theme-configuration",
        route: "theme",
        icon: null,
        parent_id: 10,
      },
    ],
  },
  {
    id: 11,
    name: "Reschedule Exam",
    slug: "reschedule-exam",
    submenus: [
      {
        id: 111,
        name: "Reschedule Exam",
        slug: "reschedule-exam",
        route: "reschedule-exam",
        icon: null,
        parent_id: 11,
      },
      {
        id: 112,
        name: "Reschedule Listing",
        slug: "reschedule-listing",
        route: "reschedule-listing",
        icon: null,
        parent_id: 11,
      },
      {
        id: 113,
        name: "Reschedule Raise",
        slug: "reschedule-raise",
        route: "reschedule-raise",
        icon: null,
        parent_id: 11,
      },
      // {
      //   id: 114,
      //   name : "Reschedule Approve",
      //   slug: "reschedule-approve",
      //   route: "reschedule-approve",
      //   icon: null,
      //   parent_id: 11,
      // },
    ],
  },
];

const sideBarIcons = {
  ["User Management"]: <HiUsers className="size-5" />,
  ["Discrepency List"]: <HiViewColumns className="size-5" />,
  ["Onboarding"]: <HiClipboardDocumentList className="size-5" />,
  ["Masters"]: <HiSwatch className="size-5" />,
  ["Bulk Upload"]: <HiDocumentPlus className="size-5" />,
  ["Reports"]: <HiDocumentMagnifyingGlass className="size-5" />,
  ["Settings"]: <HiCog className="size-5" />,
  ["NOC List"]: <HiMiniUserMinus className="size-5" />,
  ["Servicing Module"]: <HiAdjustments className="size-5" />,
  ["Reschedule Exam"]: <Hourglass className="size-5" />,
  ["Exam Config"]: <GraduationCap className="size-5" />,
  // ["Role Master"]: <IoSettingsOutline size={20} />,
};

export { ICONS, SIDE_MENU, sideBarIcons };
